services:
  - type: web
    name: ironbrew3-discord-bot
    runtime: docker
    repo: https://github.com/dctoing3-dot/ironbrew-3
    branch: main
    envVars:
      - key: TOKEN
        sync: false  # Set manual di dashboard
      - key: GuildID
        sync: false  # Set manual di dashboard
      - key: DOTNET_ENVIRONMENT
        value: Production
    buildCommand: ""
    startCommand: "/app/run-all.sh"
    healthCheckPath: /health
    autoDeploy: true
